- name: install and run nginx
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx packkage
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started 

