- name: PLAY-1
  hosts: localhost

  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "hello from the PLAY-1 AND TASK-1"

- name: PLAY-1
  hosts: localhost
  
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "hello from the PLAY-1 AND TASK-1"

